name: Build apps

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller pillow pymupdf

      - name: Build awww1(Archiwiktor Wydział Wzornictwa Setup) (macOS)
        if: runner.os == 'macOS'
        run: pyinstaller --onefile --windowed --name "awww1(Archiwiktor Wydział Wzornictwa Setup)" --add-data "Pracownie_ASP_v3.csv:." 1_ASP_Setup.py

      - name: Build awww1(Archiwiktor Wydział Wzornictwa Setup) (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --windowed --name "awww1(Archiwiktor Wydział Wzornictwa Setup)" --add-data "Pracownie_ASP_v3.csv;." 1_ASP_Setup.py

      - name: awww2(Archiwiktor Wydział Wzornictwa kompresja i nazewnictwo) (macOS)
        if: runner.os == 'macOS'
        run: pyinstaller --onefile --windowed --collect-all PIL --collect-all pymupdf --name "awww2(Archiwiktor Wydział Wzornictwa kompresja i nazewnictwo)" 2_ASP_Archiwum.py

      - name: awww2(Archiwiktor Wydział Wzornictwa kompresja i nazewnictwo) (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --windowed --collect-all PIL --collect-all pymupdf --name "2_ASP_Archiwum" 2_ASP_Archiwum.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ASP-Archiwum-${{ matrix.os }}
          path: dist/
